version: '3.6'

services:
  redis:
    image: redis:latest
    networks:
      - backend
  web:
    image: kpeiruza/docker-php-mysql-redis:latest
    networks:
      - backend
      - proxy
    deploy:
      replicas: 4
      endpoint_mode: vip
      labels:
        traefik.port: 80
        traefik.frontend.rule: "Host:sesionero.192.168.20.210.nip.io"
        traefik.docker.network: 'proxy'
networks:
  backend:
  proxy:
    external: true
